### PR TITLE
Set `$data` option in the presence of the `--data` switch

### LINKED ISSUE #93: The `--data` flag is not propagated to `Ajv`
This piece of code (modified in 9c45b1c05b346aecee30f3d2105d339a245b5ab6)
https://github.com/ajv-validator/ajv-cli/blob/f36537c89139244675df02c26a66a2a7ed7657d7/src/commands/options.ts#L97-L99

handles transforming the `--data` command line argument into the `$data` option that needs to be passed to `Ajv`. As `argv["$data"]` does not exist, the `data` flag is never propagated to the `options`.

This used to be
https://github.com/ajv-validator/ajv-cli/blob/064e1accd52ed5401f3d836f1952bec7baa0cec2/src/commands/options.ts#L104-L107
which caught the fact that `argv["$data"]` does not exist and falls back to `argv["data"]` (in line 106).

I've locally fixed this by adding `argv.$data = argv.data` to the `if` statement that checks for `data`, but I'm sure there might be more elegant solutions.

### PR DESCRIPTION
**Pull request by bauglir**
I have applied the fix as proposed in #93. I have also included some basic tests around the behavior as, looking through the issues, it looks like this is behavior that has been prone to breaking in the past as well.

Fixes #93.

### CODE REVIEW

**Comment by epoberezkin** [comment]
Thank you for spotting - I'll add the test before merging.

**Comment by epoberezkin** [comment]
ah - actually there is the test - great!

**Comment by bauglir** [comment]
Excellent, thanks for the merge!

**Comment by epoberezkin** [comment]
In 4.0.1

**Pull request merged**
