### PR TITLE
Skip registering additional schemas that match the main schema.

### LINKED ISSUE #172: how to compile/validate group of json-schema files that might reference each other in v4+
Scenario: Directory with several JSON-schema files, some of which might `$ref`erence the others. Each schema file defines a unique `$id` property.
I want to compile/validate them all at once 

This command worked in ajv-cli v3.x:
`ajv -s 'src/models/*.json' -r 'src/models/*.json'`

But with 4.x and 5.0, I get error like this:
error: schema with key or id "https://mycompany.com/this/schema/model.json" already exists

But the only file that has that id is the file itself in that directory.  It would seem that the -r flag is not excluding the file's self when checking for duplicate ids in that referenced list. 

How can I accomplish validating a group of schemas like this with the newer version?

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/ajv-validator/ajv-cli/issues/172.

Let me know if you prefer this done another way, or would like different kinds/quantities of tests!

### CODE REVIEW

**Comment by epoberezkin** [comment]
It looks like TS change that was breaking ajv now breaks this one - will look into it later.

Thanks for the PR - it looks ok!

**Comment by matanlurey** [comment]
@epoberezkin Do you want me to fix the issues in this PR? They look small, and can probably unblock pretty fast.

**Comment by epoberezkin** [comment]
absolutely, please have a look.

**Comment by matanlurey** [comment]
@epoberezkin Thanks. `npm run lint` seems to pass locally, passing over to you for a workflow run :)

**Comment by matanlurey** [comment]
Polite ping :) @epoberezkin

**Comment by epoberezkin** [comment]
It's now the same typescript change I fixed earlier in Ajv... I will look over the weekend

**Comment by matanlurey** [comment]
Sg, thanks!

**Comment by epoberezkin** [comment]
it's actually and error specific to this change - it does not happen in the master branch.

It is definitely because of the change in this PR - specifically, the change in logJSON type signature - why was it needed?

Could you please reduce the change to what is necessary, also you should be able to run the tests locally (I also enabled builds)

**Comment by xmedeko** [comment]
@matanlurey @epoberezkin maybe #196 is better approach?

**Pull request closed without merging**
